### PR TITLE
remove CGI + switch to dbh

### PR DESCRIPTION
**Pull request by asb-capfan**
a) switched from CGI to CGI::Simple
b) instead of providing credentials, the user has to provide a database
handle

### CODE REVIEW

**Review by srchulo — CHANGES_REQUESTED** [review]
This is small, but could you make database_handle "dbh" instead? Other than that it looks great!

**Comment by srchulo** [comment]
Also, it looks like user, host, db, port, etc all of their documentation is still there.

**Review by asb-capfan — COMMENTED** [review]
Renaming to dbh done. It's actually what I prefer, but it's less mnemonic.
Removed obsolete code. I don't know why I didn't realize it in the first place :-s

**Comment by asb-capfan** [comment]
Should be OK now.

**Review by srchulo — CHANGES_REQUESTED** [review]
In the documentation under "dbh", you have

$dt->port(DBI->connect...), which should be $dt->dbh

Also, I don't actually see a dbh subroutine, so any calls to $dt->dbh would fail

**Comment by srchulo** [comment]
And yeah, database_handle is more explicit, but I think most people know what dbh means since it's fairly common, even across languages.

**Comment by asb-capfan** [comment]
Let's try again. It's so much easier with an actual test environment...

**Review by srchulo — COMMENTED** [review]
Looks great! Thanks!

**Review by srchulo — APPROVED** [review]

**Pull request merged**
